//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RecipeID { get; set; }
        public string RecipeTitle { get; set; }
        public string RecipeStep1 { get; set; }
        public string RecipeStep2 { get; set; }
        public string RecipeStep3 { get; set; }
        public string RecipeStep4 { get; set; }
        public string RecipeStep5 { get; set; }
        public string RecipeStep6 { get; set; }
        public string RecipeStep7 { get; set; }
        public string RecipeStep8 { get; set; }
        public string RecipeStep9 { get; set; }
        public string RecipeStep10 { get; set; }
        public string Ingrediant1 { get; set; }
        public string Ingrediant2 { get; set; }
        public string Ingrediant3 { get; set; }
        public string Ingrediant4 { get; set; }
        public string Ingrediant5 { get; set; }
        public string Ingrediant6 { get; set; }
        public string Ingrediant7 { get; set; }
        public string Ingrediant8 { get; set; }
        public string Ingrediant9 { get; set; }
        public string Ingrediant10 { get; set; }
    }
}
