//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RecipeID { get; set; }
        public string RecipeTitle { get; set; }
        public string RecipeStep1 { get; set; }
        public string RecipeStep2 { get; set; }
        public string RecipeStep3 { get; set; }
        public string RecipeStep4 { get; set; }
        public string RecipeStep5 { get; set; }
        public string RecipeStep6 { get; set; }
        public string RecipeStep7 { get; set; }
        public string RecipeStep8 { get; set; }
        public string RecipeStep9 { get; set; }
        public string RecipeStep10 { get; set; }
        public string Ingredient1 { get; set; }
        public string Ingredient2 { get; set; }
        public string Ingredient3 { get; set; }
        public string Ingredient4 { get; set; }
        public string Ingredient5 { get; set; }
        public string Ingredient6 { get; set; }
        public string Ingredient7 { get; set; }
        public string Ingredient8 { get; set; }
        public string Ingredient9 { get; set; }
        public string Ingredient10 { get; set; }
    }
}
